build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank Accounts"
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybytes.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
